CREATE TABLE `modstud_st1` (
        `ID` INT(11) NOT NULL AUTO_INCREMENT,
        `NAME` VARCHAR(65536) NOT NULL,
        `SURNAME` VARCHAR(65536) NOT NULL,
        `PATRONYMIC` VARCHAR(65536) NOT NULL,
        PRIMARY KEY(ID)
    );

CREATE TABLE `modstud_teach1` (
        `ID` INT(11) NOT NULL AUTO_INCREMENT,
        `NAME` VARCHAR(65536) NOT NULL,
        `SURNAME` VARCHAR(65536) NOT NULL,
        `PATRONYMIC` VARCHAR(65536) NOT NULL,
        PRIMARY KEY(ID)
    );

CREATE TABLE `modstud_tt1` (
        `ID` INT(11) NOT NULL AUTO_INCREMENT,
        `DATETIME` TIMESTAMP NOT NULL,
        `ClASSROOM` INT(11) DEFAULT 0,
        `LESSON` VARCHAR(65536) NOT NULL,
        `ID_TEACH` INT(11) DEFAULT 0,
        PRIMARY KEY(ID)
    );

CREATE TABLE `modstud_category1` (
        `ID` INT(11) NOT NULL AUTO_INCREMENT,
        `TABLE_ST_ID` INT(11) DEFAULT 0,
        `ID_STUD` INT(11) DEFAULT 0,
         PRIMARY KEY(ID)
    );



/*
INSERT INTO modstud_st (ID,NAME,SURNAME,PATRONYMIC)
VALUES (1, 'STUDNAME1', 'STUDSURNAME1', 'STUDPATRONYMIC1');

INSERT INTO modstud_st (ID,NAME,SURNAME,PATRONYMIC)
VALUES (2, 'STUDNAME2', 'STUDSURNAME2', 'STUDPATRONYMIC2');

INSERT INTO modstud_st (ID,NAME,SURNAME,PATRONYMIC)
VALUES (3, 'STUDNAME3', 'STUDSURNAME3', 'STUDPATRONYMIC3');

INSERT INTO modstud_st (ID,NAME,SURNAME,PATRONYMIC)
VALUES (4, 'STUDNAME4', 'STUDSURNAME4', 'STUDPATRONYMIC4');

INSERT INTO modstud_st (ID,NAME,SURNAME,PATRONYMIC)
VALUES (5, 'STUDNAME5', 'STUDSURNAME5', 'STUDPATRONYMIC5');




INSERT INTO modstud_teach (ID,NAME,SURNAME,PATRONYMIC)
VALUES (1, 'TEACHNAME1', 'TEACHSURNAME1', 'TEACHPATRONYMIC1');

INSERT INTO modstud_st (ID,NAME,SURNAME,PATRONYMIC)
VALUES (2, 'TEACHNAME2', 'TEACHSURNAME2', 'TEACHPATRONYMIC2');

INSERT INTO modstud_st (ID,NAME,SURNAME,PATRONYMIC)
VALUES (3, 'TEACHNAME3', 'TEACHSURNAME3', 'TEACHPATRONYMIC3');



*/